### ISSUE TITLE
OpenSSL error using example

### ISSUE THREAD

**Issue by ruprict** [phrase/phraseapp-ruby#1]
If I use the example in the README, I get

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /Users/ggoodrich/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
```

To be clear, I created an access token (read, write) in my user settings page, and replaced `YOUR_ACCESS_TOKEN` in the following snippet:

```
# Require the gem
require 'phraseapp-ruby'

# Setup authentication with an access token
auth_handler = PhraseApp::Auth::AuthHandler.new(token: "YOUR_ACCESS_TOKEN")
PhraseApp::Auth.register_auth_handler(auth_handler)

# Create a client
client = PhraseApp::Client

# List projects page 1 and list 10 projects per_page
rsp, err = client.projects_list(1, 10)
```

Using Ruby 2.2.2

**Comment by kevvvvv** [comment]
Hi ruprict, can you try running

    rvm osx-ssl-certs status all
    rvm osx-ssl-certs update all

And see if this fixes the problem?

**Comment by ruprict** [comment]
Hey @kevvvvv, did that, did not fix problem.

Any other suggestions?

**Comment by kevvvvv** [comment]
What OpenSSL version are you using

    $ openssl version

**Comment by ruprict** [comment]
```
[3] pry(main)> client = PhraseApp::Client
=> PhraseApp::Client
[4] pry(main)> rsp, err = client.projects_list(1,10)
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
from /Users/ggoodrich/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
[5] pry(main)> exit
➜  phraseapp  openssl version
OpenSSL 1.0.2c 12 Jun 2015
➜  phraseapp
```

**Comment by ruprict** [comment]
@kevvvvv, not sure if this is important, but:
```
ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
OpenSSL 1.0.1j 15 Oct 2014
```

**Comment by Enriikke** [comment]
I was able to replicate this bug in version `OpenSSL 0.9.8zf 19 Mar 2015` in OSX. Upgrading to version `OpenSSL 1.0.2d 9 Jul 2015` fixed the issue on my end.

**Comment by ruprict** [comment]
So, I guess brew has to upgrade OpenSSL piecemeal? I did `brew upgrade openssl` this morning after @kevvvv mentioned it, got the Jun 2015 version, then did it again after @Enriikke and got Jul 2015 version. 

Regardless, it isn't giving me that error any more.  :)

**Comment by Enriikke** [comment]
I feel that this needs to be documented somewhere, so users know which versions of OpenSSL are supported :smiley:

**Comment by kevvvvv** [comment]
Thank you @Enriikke for pointing this out.
Glad it is working now @ruprict!
