### ISSUE TITLE
OpenStruct#to_h returns nil in JRuby 1.7.20 and Ruby 1.9.3

### ISSUE THREAD

**Issue by jjustaments** [phrase/phraseapp-ruby#10]
Hi,

We use JRuby 1.7.20 and the same problem is also in Ruby 1.9.3
With these versions of Ruby t_h method returns nil value.
As a result locale_download and other methods do not work correctly.

Best regards,
Jānis.

**Comment by kennell** [comment]
Hi @jjustaments and thank you for pointing this out. This is fixed in gem version 1.1.2.
