### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#14]
Hi,

We're currently running version `1.1.0`, and I'm not sure if the changes in later versions are useful or will require changes in how we use the gem.

I tried to read the commit history, but the code is auto-generated so I can't easily see what changes have been made.

Is it possible to have a history or changelog file that lists what changes have been made in each version (particularly breaking ones)?

**Comment by gfrey** [comment]
Hi,

you're right, we should better document the changes! Thanks for the feedback.

Going to the latest version (1.2.4) would give you essentially:

* support for fallback locales on download (see https://phraseapp.com/docs/api/v2/locales/#download)
* support for file encoding on upload (see https://phraseapp.com/docs/api/v2/uploads/#create)
* improved error handling (see https://github.com/phrase/phraseapp-ruby/commit/6b05530faecb60f05ff76b7ec76c05093f0a385a)
* some internal fixes

I hope this answers your question.

**Comment by nTraum** [comment]
Hi @gfrey,

have you thought about introducing a changelog file to the project? I'm in a similar boat as @yob, we'd like to upgrade to the latest version (coming from 1.3.3) but there's no information available on what has changed.

https://github.com/mperham/sidekiq/blob/master/Changes.md in my opinion is a good example of what a changelog should contain.

**Comment by theSoenke** [comment]
We now try to list the changes for each release: https://github.com/phrase/phraseapp-ruby/releases

**Comment by yob** [comment]
Thanks!
