### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by fphilipe** [phrase/phraseapp-ruby#16]
Guys, look at this line: https://github.com/phrase/phraseapp-ruby/blob/45635f1536a5a9d8a646802b7f59056926b73e99/lib/phraseapp-ruby.rb#L979-L981

This makes no sense at all and results in the function calling itself over and over again. Am I missing something?

**Comment by sacry-dyn** [comment]
@fphilipe thank you for noticing. The library is autogenerated so we have to carefully look into it. Seems like an obvious mistake.

**Comment by lime** [comment]
Is the actual source that you generate this library from available somewhere? It would make it much easier to contribute to the project.

**Comment by sacry-dyn** [comment]
@lime at the moment the client generation is private. Currently a lot of information are put into the generation that should not be publicly available like build information etc. We would have to carefully consider what to outsource and what not. 

@fphilipe I opened a pull request here that should fix your problem:

https://github.com/phrase/phraseapp-ruby/pull/17

**Comment by kennell** [comment]
We just released [version 1.2.6](https://rubygems.org/gems/phraseapp-ruby/versions/1.2.6) of the gem that addresses these issues.
