### ISSUE TITLE
Documented authentication technique is wrong

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#2]
Hi,

The README suggests creating an oauth token, then registering a handler like so:

```ruby
auth_handler = PhraseApp::Auth::AuthHandler.new(token: "YOUR_ACCESS_TOKEN")
PhraseApp::Auth.register_auth_handler(auth_handler)
```

However, it seems an oauth token also requires a username to be provided:

```ruby
auth_handler = PhraseApp::Auth::AuthHandler.new(username: "YOUR_USERNAME", token: "YOUR_ACCESS_TOKEN")
PhraseApp::Auth.register_auth_handler(auth_handler)
```

Tested on version `1.0.17`

**Comment by kevvvvv** [comment]
As the README suggests, giving the access token should be sufficient.
I can't seem to reproduce the issue, what error are you getting when not providing a username?

**Comment by yob** [comment]
Hmm, yesterday I was getting a 401 but today it's working. I assume I was doing something silly yesterday - sorry for the noise!
