### ISSUE TITLE
RequestErrors should inherite from StandardError

### ISSUE THREAD

**Issue by nesQuick** [phrase/phraseapp-ruby#22]
So I can raise it and get them into my ususal error handling flow

**Comment by sacry-dyn** [comment]
Hey, we will look into it and come back to you. That part of the code is auto-generated.

**Comment by sacry-dyn** [comment]
@nesQuick after some consideration we decided against inheriting from Exception. Short story: It is against convention to inherit from Exception but rather from StandardError. We do not want to automatically capture errors that are part of the Exception hierarchy like `NoMemoryError` but only those of StandardErrors. See here for the concrete reasoning:

http://blog.honeybadger.io/ruby-exception-vs-standarderror-whats-the-difference/

We could however think about inheriting from StandardError as it seems the classes are currently not inheriting from anything.

**Comment by nesQuick** [comment]
@sacry-dyn cool. I did not know about it. Actually I do not care if it inherits from Exception or StandardError. It's more that raising something would help or that at least the errors you return would be instantly raisable.

**Comment by sacry-dyn** [comment]
@nesQuick we will look into it and come back to you when we have something. It might take a little time as it is integrated into our code generation flow.

**Comment by sacry-dyn** [comment]
Hey, we are sorry that it took a bit. We addressed the issue here:

https://github.com/phrase/phraseapp-ruby/commit/e700e79281a79c3fadead50a85fbe63c19e37dd8

Could you verify that this works as intended?

**Comment by nesQuick** [comment]
Yeah that's what I was expecting, now another release would be great :)

**Comment by sacry-dyn** [comment]
Sorry for the late reply. We updated the gem to 1.3.2 here https://rubygems.org/gems/phraseapp-ruby
