### ISSUE TITLE
Type error in Client#upload_create

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#3]
`Client#upload_create` contains the following check:

```ruby
if params.present?
  unless params.kind_of?(PhraseApp::RequestParams::UploadCreateParams)
    raise PhraseApp::ParamsHelpers::ParamsError.new("Expects params to be kind_of PhraseApp::RequestParams::LocaleFileImportParams")                           
  end
end
```

The class in the conditional and exception message don't match. It seems that `PhraseApp::RequestParams::UploadCreateParams` isn't a valid class - should it be `PhraseApp::RequestParams::LocaleFileImportParams`?

Tested on `1.0.17`.

**Comment by kevvvvv** [comment]
Thank you for pointing this out @yob. This has been fixed in the latest release (version 1.0.18).
