### ISSUE TITLE
Passing 0 as per_page parameter on locales_list returns 500

### ISSUE THREAD

**Issue by caldofran** [phrase/phraseapp-ruby#30]
We were using this piece of code for a very long time `all_locales = phraseapp_client.locales_list(PROJECT_ID, 0, 0)` to get all locales. But we try our script currently and we are getting a 500 error from Phraseapp client.
After some trials, we realised that passing 0 as per_page parameter was causing the 500 error.
We've checked the documentation but we didn't find anything about this issue.
Was there any change in the API about pagination that is not documented?
Is there any way to ask "give me all locales" without passing `100` as per_page parameter? Something like `0` to get the whole list.
In addition, getting a 500 error in this case I think is a bit misleading.
By the way, we found the problem in version `phraseapp-ruby (1.3.3)`.

Thanks in advanced!

**Comment by tobstarr** [comment]
Hi @caldofran. Thanks for contacting us.

Indeed, receiving status code 500 is not what you should expect from our API. We will look into your issue and get back to you soon.

**Comment by tobstarr** [comment]
You are correct, passing 0 as per_page leads to an exception and should result in an error code 4xx (passing 0 to get all is not supported but also not documented).

Due to performance reasons all our API endpoints are paginated and all have a maximum value for the per_page value. To get a list of all your locales you would iterate using the page parameter like this:

```
def list_all_locales(client, project_code, per_page = 1)
  list = []
  page = 1

  while true
    res, err = client.locales_list(project_code, page, per_page)
    if !err.nil?
      raise err
    end
    break if res.count == 0
    list += res
    page += 1
  end
  return list
end
```

Hope I that solves your issue.

**Comment by caldofran** [comment]
Thanks @tobstarr for your quick answer.

It would be great to have this documented somehow.

**Comment by tobstarr** [comment]
@caldofran you mean that passing 0 as per_page does not give you all results? Or just document the snippet for how to iterate a collection?

My personal expectation would be that if I pass 0 as per_page I would not get any results at all but also getting an exception that 0 is not a valid input would be okay. I would rather not specifically document that 0 __does not__ give you all results. The error message should give you a hint about the invalid input though.
