### ISSUE TITLE
…/phraseapp-ruby/request_handler.rb:157:in `handleResponseStatus': not found (RuntimeError)

### ISSUE THREAD

**Issue by Calamari** [phrase/phraseapp-ruby#31]
If I write this program:

```
  credentials = PhraseApp::Auth::Credentials.new(token: 'TOKEN')
  client = PhraseApp::Client.new(credentials)
  params = PhraseApp::RequestParams::TranslationKeyParams.new(name: 'key')
  resp, err = client.key_create('PROJECT_ID', params)
```

I get this error:

```
…/.rvm/gems/ruby-2.3.1/gems/phraseapp-ruby-1.3.3/lib/phraseapp-ruby/request_handler.rb:157:in `handleResponseStatus': not found (RuntimeError)
	from …/.rvm/gems/ruby-2.3.1/gems/phraseapp-ruby-1.3.3/lib/phraseapp-ruby/request_handler.rb:145:in `http_send'
	from …/.rvm/gems/ruby-2.3.1/gems/phraseapp-ruby-1.3.3/lib/phraseapp-ruby/request_handler.rb:103:in `send_request'
	from …/.rvm/gems/ruby-2.3.1/gems/phraseapp-ruby-1.3.3/lib/phraseapp-ruby.rb:3286:in `key_create'
	from create_texts.rb:14:in `create_resource'
	from create_texts.rb:19:in `<main>'
```

But that's pretty much the example of the documentation, so it is supposed to work. Or at least not fail with an `RuntimeError`.

**Comment by docstun** [comment]
@Calamari did you enter a proper value for TOKEN and PROJECT_ID? If yes, could you share the project id and the last 8 digits of your token with us? (Please send them to our support team, you don't need to post them here) https://phraseapp.com/contact

Thanks!

**Comment by tobstarr** [comment]
@Calamari closing this, feel free to comment if you still have the mentioned problems.

**Comment by y9v** [comment]
hi! we are experiencing the same problem.

We have sidekiq jobs that are creating translation keys, and sometimes (quite rarely), we get a "not found" runtime exception. On retry the same job passes successfully.

Maybe it makes sense to add some context to this exception, at least what was not found? Also having a proper exception type would be nice.

**Comment by theSoenke** [comment]
Hi, sorry for my late response. I agree that the error message is not very helpful here. Did you experience the same issue again lately? The API should only respond with a not found if the project id is not correct or the access token does have permissions to see the project (e.g. for a user with the developer role which is not assigned to the project). 

In case you should see this issue again could you please contact us at https://phraseapp.com/contact or via the chat on phraseapp.com? Then we can have a closer look at what caused the request to fail
