### ISSUE TITLE
I18n.t returns "{{__phrase_.......__}}" instead of translation

### ISSUE THREAD

**Issue by ncri** [phrase/phraseapp-ruby#36]
After adding the gem, trying to receive translations via the I18n.t helper I get 

```
I18n.t("de-CH")
 => "{{__phrase_de-CH__}}" 
```

Any idea what I need to do to get it working?

**Comment by ncri** [comment]
I now assume this is actually part of "phraseapp-in-context-editor-ruby" and correct behavior?

**Comment by theSoenke** [comment]
Hi @ncri, the gem phraseapp-in-context-editor-ruby should only be used to integrate our [InContext-Editor](https://phraseapp.com/docs/guides/in-context-editor). For the InContext-Editor to work all keys will be wrapped in `{{__phrase_keyname__}}`. This will then be replace with the actual content by the InContext-Editor and can be translated in place on the web page.

For production systems it is not necessary to use this gem. Instead you can for example only use the default rails i18n library to to serve translations from yml translation files.

Does this already clarifies it? Let me know if you have any further questions

**Comment by ncri** [comment]
Thanks! I just figured that out too. ;-)
