### ISSUE TITLE
Pagination not supported

### ISSUE THREAD

**Issue by andi-dev** [phrase/phraseapp-ruby#37]
As far as I can see methods like 'keys_list' are only returning the responses body (as json), thus I see no chance to access the link header field mentioned in the API docs.

Our use case is to query all missing translations for a locale, and it is quite inconvenient to solve this issue without at least knowing the total number of results.

Or am I missing something?

**Comment by theSoenke** [comment]
Hi @andi-dev, the method `keys_list` does have the following signature: `keys_list(project_id, page, per_page, params)`. To get all pages you would have to increment the page until the response is empty. In case you want to access the header you could also access the [API](https://phraseapp.com/docs/api/v2/) directly without this wrapper
