### ISSUE TITLE
Comparing branches

### ISSUE THREAD

**Issue by kroussevrb** [phrase/phraseapp-ruby#49]
When will support be added for https://developers.phrase.com/api/#branches_compare so that I know whether there is a conflict that needs to be resolved before trying to merge a branch via the terminal?

**Comment by rlisowski** [comment]
@kroussevrb you can try our new autogenerated/experimental ruby gem https://github.com/phrase/phrase-ruby. The new gem is based on the OpenAPI and includes [compare branches endpoint](https://github.com/phrase/phrase-ruby/blob/master/docs/BranchesApi.md#branch_compare)

**Comment by theSoenke** [comment]
The new gem is no longer experimental and I'll close this issue for now
