### ISSUE TITLE
ErrorResponse with blank message

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#5]
I attempted to download a YAML file for a locale with the following code:

```ruby
params = PhraseApp::RequestParams::LocaleDownloadParams.new(
  file_format: "yaml",
  tag: "my-tag",
)
res = PhraseApp::Client.locale_download(@project_id, @locale_id, params)
```

Unfortunately, `yaml` isn't a valid format - it should be `yml`. However, it took me a while to establish that, as the `ErrorResponse` that I got back had a `nil` message. I eventually established the mistake I'd made by inserting `puts` statements into the gem code and manually inspect the results at various points.

It'd be great if `ErrorResponse#message` could return a helpful message.

Tested on `1.0.17`.

**Comment by kevvvvv** [comment]
Hi @yob - thank you for reporting this issue. We will improve that error response.

Also, for future reference, the formats and their API extensions are documented here: http://docs.phraseapp.com/guides/formats/
