### ISSUE TITLE
Uploading a flle creates the wrong tags

### ISSUE THREAD

**Issue by yob** [phrase/phraseapp-ruby#8]
Hi,

I'm uploading a YAML file with the following code and `1.0.20`:

```ruby
params = PhraseApp::RequestParams::LocaleFileImportParams.new(
  file: "tmp/test.yml",
  file_format: "yml",
  tags:  ["testing"],
  skip_upload_tags: true,
  update_translations: true,
)
res = PhraseApp::Client.upload_create(@project_id, params)
```

Note the use of an Array for `tags` (as discussed in #6) and booleans for `skip_upload_tags` (as discussed in #7).

The upload completes successfully, however the keys are tagged with `__testing__` rather than `testing`.

**Comment by docstun** [comment]
Hi @yob - we're working on a fix for this, should be available in the next 24 hours.

**Comment by yob** [comment]
Thanks @docstun

**Comment by yob** [comment]
If it helps, I'm happy to try out the fix when it's on master and before a release is cut

**Comment by kevvvvv** [comment]
@yob the latest version of the gem (1.0.21) should fix this issue. Thanks.
