### ISSUE TITLE
wrong constant name Net::HTTP::Get::REQUEST_HAS_BODY

### ISSUE THREAD

**Issue by jjustaments** [phrase/phraseapp-ruby#9]
Hi,

Not working with JRuby 1.7.20 (https://github.com/jruby/jruby/issues/1487)
These lines causes the error https://github.com/phrase/phraseapp-ruby/blob/master/lib/request_handler.rb#L92-L93
To make it compatible, we can use
```ruby
Net::HTTP.const_get(method.capitalize).const_get(:REQUEST_HAS_BODY)
```
instead of
```ruby 
Module.const_get("Net::HTTP::#{method.capitalize}::REQUEST_HAS_BODY")
```

**Comment by kennell** [comment]
Hi @jjustaments - thanks for pointing this out. This is fixed in gem version 1.1.1.
